# ______ _            _                                   _   
# | ___ \ |          | |                                 | |  
# | |_/ / | __ _  ___| | _____ _   _ _ __ _ __ __ _ _ __ | |_ 
# | ___ \ |/ _` |/ __| |/ / __| | | | '__| '__/ _` | '_ \| __|
# | |_/ / | (_| | (__|   < (__| |_| | |  | | | (_| | | | | |_ 
# \____/|_|\__,_|\___|_|\_\___|\__,_|_|  |_|  \__,_|_| |_|\__|
# http://patorjk.com/software/taag/#p=testall&f=Blocks&t=Blackcurrant%0A                                                            

# Almost all the things in the website can be customized from here.
# Changing title and description according to your website requirement is important.


title: Inapuri Chess World
short-description: Professional Chess Coach (WFM)
description: Online chess coaching.
email: john@doe.com # The contact form submission will be done to this email address.
url: https://inapurichess.com
default-image: /images/ramya-inapuri-online-chess-coach.jpg # This image will be shown on sharing any page on social media. For example: Homepage, about page etc. This image should be bigger than 200x200px. This image is not used for posts. Posts use their own image mentioned in individual posts.

# Author details shows up at the end of every article
author: 
    name: Ramya Inapuri
    bio: ""
    image: ramya-inapuri-online-chess-coach.jpg # Choose a 200x200px image and place it inside /images directory.
    facebook: https://facebook.com/inapurichessworld.com
    twitter: https://twitter.com/
    linkedin: https://www.linkedin.com/
    github: https://github.com/
    phone: '+1-609-955-0355'
    email: 'kids.chessworld@gmail.com'

#                                                                                 
#   ,-----.       ,--.                   ,---.  ,--.                              
#  '  .--./ ,---. |  | ,---. ,--.--.    '   .-' |  ,---.  ,---. ,--,--,--. ,---.  
#  |  |    | .-. ||  || .-. ||  .--'    `.  `-. |  .-.  || .-. :|        || .-. : 
#  '  '--'\' '-' '|  |' '-' '|  |       .-'    ||  | |  |\   --.|  |  |  |\   --. 
#   `-----' `---' `--' `---' `--'       `-----' `--' `--' `----'`--`--`--' `----' 
#                                                                                 
# There are 5 color schemes to choose from. 
# Use numbers 1 to 4 to address them. 
# 1 is Default and 5 is dark. 
# Choose 0 for custom colors
# color-scheme: 1
# If color-scheme is 0 then enter the color values below



# Kramdown is the default markdown processor used. It is supported by Github.
markdown: kramdown

# This defines how the URLs should look like.
permalink: /blog/:title/

# Pagination - Posts per page in the blog index.
paginate: 4
paginate_path: /blog/page:num/



# Jekyll will read contents inside _pages only if we tell it to.
include: 
    - _pages

# Google Ananlytics Tracker.
# Sign up with Google analytics and replce with your analytics ID.
analytics:   

# Table of contents in each post
# Change the value to 'no' if Table of Contents is not required.
toc:  yes

# Share buttons
# Change it to `no` to remove share buttons.
share: yes 


# Comments by Disqus 
# Sign up with Disqus to get your shortcode. Leave it blank if you do not want to run diqus code on the website.
# Leave it blank to remove disqus completely.
disqus: inapurichessworld 


# Define whether recent posts should be shown at the bottom of each post.
# Change it to `no` to remove recent posts.
recent-posts: yes 

#                                                                                  
#   ,-----.                                                    ,--.                
#  '  .--./ ,---. ,--,--,--. ,---. ,--.--. ,---.  ,---.  ,---. `--' ,---. ,--,--,  
#  |  |    | .-. ||        || .-. ||  .--'| .-. :(  .-' (  .-' ,--.| .-. ||      \ 
#  '  '--'\' '-' '|  |  |  || '-' '|  |   \   --..-'  `).-'  `)|  |' '-' '|  ||  | 
#   `-----' `---' `--`--`--'|  |-' `--'    `----'`----' `----' `--' `---' `--''--' 
#                           `--'                                                   
# All compression variables are declared here.

sass:
 style: compressed
 
#compress.html
compress_html:
  clippings: [html, head, meta, title, link, body, div, script, header, footer]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [] 

####################################################################################################

# destination: _blackcurrant

exclude: 
    - .git


# These plugins are supported by github by default and can be installed locally using ruby gems
plugins: 
    - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
    - jekyll-feed       # Adds feed to the website at /feed.xml
    - jekyll-paginate   # Used for sorting posts by page numbers.
    - jekyll-seo-tag    # Adds all the important SEO meta tags by default.
