
title: WebJeda | A modern web development blog
description: "Webjeda Sidebar is an elegant theme which offers a nice toggleable sidebar. The theme stands out in its features like changable color scheme and pre-installed sharebar, analytics and disqus. It is suitable for all kinds of blogging."
author: sharath dt


author-image: sharathdt.jpg

baseurl: ""  # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown


#color scheme
sidebar-color: '#000'       #those apostrophes are important
accent-color: '#F62459'     #those apostrophes are important


#social
facebook: https://www.facebook.com/
twitter: https://twitter.com/
twitter-handle: '@sharathdt'     #for twitter button on author section #those apostrophes are important
github: https://github.com/
youtube: https://www.youtube.com/channel/
email: mailto:hello@webjeda.com
feedburner-subscribe: https://feedburner.google.com/fb/a/mailverify?uri=webjedablog&amp;loc=en_US

#Other
analytics: 'UA-65551407-1'
disqus-shortname: webjeda-sample    #Disqus comments
google-custom-search-cx: '017575011755499056211:vwrwldvgq6s'        #Create Custom Search Engine(CSE) with google and find this ID in the code they provide.


destination: ./_site
permalink: /:title/
paginate: 6
paginate_path: /page:num/

sass:
    style: compressed
    
gems: [jekyll-paginate]

author-image: /img/ramya-inapuri.jpg
