
title: ICW | Inapuri Chess World - Online Chess Coaching
description: "Inapurichessworld is a company found to teach chess to kids online. We have a uniwue way of teaching and a good success rate as well."
author: sharath dt


author-image: sharathdt.jpg

baseurl: ""  # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown


#color scheme
sidebar-color: '#000'       #those apostrophes are important
accent-color: '#F62459'     #those apostrophes are important


#social
facebook: https://www.facebook.com/
twitter: https://twitter.com/
twitter-handle: '@sharathdt'     #for twitter button on author section #those apostrophes are important
github: https://github.com/
youtube: https://www.youtube.com/channel/
email: mailto:hello@webjeda.com
feedburner-subscribe: https://feedburner.google.com/fb/a/mailverify?uri=webjedablog&amp;loc=en_US

#Other
analytics: ''
disqus-shortname:     #Disqus comments
google-custom-search-cx: ''        #Create Custom Search Engine(CSE) with google and find this ID in the code they provide.


destination: ./_site
permalink: /:title/


sass:
    style: compressed
    

author-image: /img/ramya-inapuri.jpg
